[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://docs.twown.com/">Twown</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/docs/alarm/alarmpaw">Alarm version 1.0 just shipped!</a>'

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
    footer = 'Gebaut mit <a class="text-muted" href="https://docs.twown.com/">Hyas</a>'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://docs.twown.com">Doks v0.5</a>'

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
    languageTag = "nl-NL"
    titleAddition = "Modern documentatie-thema"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    titleHome = "Doks thema"
    footer = ' <a href="https://docs.twown.com/">Twown</a>'
    alertText = '<a class="alert-link stretched-link" href="https://docs.twown.com">Twown</a>'
